### ISSUE TITLE
Open transaction as generic.

### ISSUE THREAD

**Issue by petterek** [CoreyKaylor/Lightning.NET#13]
Maybe implement an generic version of the BeginTransaction and attach the the string, or int key provider to the trans. 

Would make it easier to work with..

**Comment by CoreyKaylor** [comment]
I'm spiking out an alternative to the providers at the moment. I should have something to share publicly in a few days.

**Comment by petterek** [comment]
Great, I'm just starting to use the library so it's possible I'm missing out on some of the ways to do things..  

I could of course add a abstration layer between my code and yours to fix it, but I thought I'll file an issue instead :)

**Comment by ilyalukyanov** [comment]
Petterek, currently you don't have to use providers directly. You can use extension methods located in LightningDB.BasicExtensions and LightningDB.Extensions ([these](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/BasicExtensions/LightningDatabaseBasicExtensions.cs) and [these](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/Extensions/LightningDatabaseExtensions.cs) respectively).
An approach with generic BeginTransaction looks like more consistent. Lets wait for Corey's commits first and then we consider our further steps on this. 
I definitely should reconsider API design so any feedback on inconveniences is valuable. Thanks for an issue)

**Comment by ilyalukyanov** [comment]
petterek, please have a look at master. I think we don't need generic BeginTransaction now. What do you think?
If you're agree i close this issue.

**Comment by petterek** [comment]
Seemed ok to me. 
The only thing that i'm not comfortable with is the sending of the _db as a parameter when retriving data through a transaction. 
Could we just pass the _db in the constructor of the transaction? 
Actually why do we have the reference to the _db at all?

**Comment by ilyalukyanov** [comment]
We can't pass it to a ctor because a transaction can work with several databases.
Databases here is close to tables in relational world. So, these transaction methods just saying "put this key-value pair to this table" etc.
It would be more convenient if the first parameter was database name except the actual db object, but in this case we'd have to retrive a db handle by name every time the method is called. I can introduce these feature as an additional extension methods for those who prefer convenience over maximum speed.

**Comment by petterek** [comment]
Ofcourse.. My bad..
