### ISSUE TITLE
Problem with large MapSize (lmdb compiled with MinGW)

### ISSUE THREAD

**Issue by runaum** [CoreyKaylor/Lightning.NET#30]
It's really strange, but original binaries (lmdb64.dll) from NuGet package cannot open environment with MapSize > ~20Mb. mdb_env_open returns 0x08 (ERROR_NOT_ENOUGH_MEMORY). I check ruby wrapper for lmdb under windows, it cannot do it too: "Exec format error". There is no problem on linux.

So, I get your VS solution for liblmdb (mdb sources were updated from original repository), build it and it works fine, no problems with MapSize on both machines.

Can you confirm this strange things?

**Comment by ilyalukyanov** [comment]
Thank your for the issue, I will have a look on this in a couple of days. It could be related to some cross-compilation troubles and I maybe I should optimize the build process. Both 32 and 64 bit dlls are compiled in the MinGW environment and the 64 one is known to have some bugs. Probably, It also could be a lmdb bug, which has been fixed in a more recent version. Anyway, I'll try to fix this.

**Comment by ilyalukyanov** [comment]
I had a chance to check this issue and with the latest version of lmdb sources at least in my environment all seems fine. I've added a test that creates and opens an environment of mapsize = 55mb, which successfully passes. Please have a look if this is still an issue for you with ver 0.8.3 from nuget.

**Comment by runaum** [comment]
All is ok, but from those time I use separated builds: I build lmdb from the official gitorius repo and use it with yout wrapper.
