### ISSUE TITLE
Update for new dnx runtimes

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#48]
After a long hiatus of inactivity it's finally a priority for me to get this working for our needs again. I would like to get it all running on dnx and have an idea of what it will take to get there.

Dnx does have a new project system that simplifies the project structure, but would require change. It would allow us to target "dnxcore50", "dnx451", "net45", "net40" very easily though.

The dnx runtime doesn't guarantee the same behavior that mono does regarding alternate file extension searching for DllImport, but there is another approach to dynamically assign delegates to the function pointers in the native libs. This is how the new kestrel web server is doing things under the covers.

The good news is that the entire nuget experience is significantly improved on dnx and it can remove a lot of the complexities being dealt with today through the rakefile, ripple, etc.

I'm also thinking that the payoff in the end of embedding the submodule for lmdb isn't making it much easier for as often as things seem to be updated. I'm wondering if including the dll, dylib, etc. (the way you had it to begin with) is going to be easier in the long run to simplify the approachability of the project.

Also, I can setup a travis-ci, and appveyor CI build to verify Windows and Linux behavior is working. I might also suggest that each CI produces a nuget and publishes to a myget feed. Then there is a very easy step to publish to the public nuget feeds on demand from myget.

Anything sound unreasonable?

**Comment by CoreyKaylor** [comment]
This new approach would also eliminate the need for native facade code generation.

**Comment by buybackoff** [comment]
Re: delegates vs DllImport see this question http://stackoverflow.com/questions/27981719/c-sharp-native-interop-why-most-libraries-use-loadlibrary-and-delegates-instea. This question was asked in the context of this library. After it, in my fork of this library I use LoadLibrary + DllImport without any facades or delegates or code generation.

**Comment by CoreyKaylor** [comment]
Mind pointing me to your use of LoadLibrary, or are you doing that within the context of your running application? I glanced, but didn't see anything different in your repo beyond organization and project structure. I don't have any objection to keeping the DllImport if the combination of DllImport and LoadLibrary do the trick and works in the new dnxcore. It's good to have the added context regarding performance.

**Comment by buybackoff** [comment]
Sorry, now my fork is completely incompatible and private - probably native calls are the only things that left. The idea is that after calling `LoadLibrary` you could use `DlIImport` as usual. All you need to do is to point `LoadLibrary` to the right file. See this as a comprehensive example: https://bitbucket.org/MDukhan/yeppp/src/40148ba4cdd00b03dfa880f6b7cecce83979c9d3/bindings/clr/sources-csharp/library/Loader.cs?at=default

**Comment by CoreyKaylor** [comment]
Yeah, that's what I assumed it would look like. I've started down that path in a branch and we'll see where I come out. I know there has been some discussion regarding improvements to DllImport for xplat as well, but too early to tell how that will end up.

**Comment by buybackoff** [comment]
Actually, in Yeppp they changed calling from DllImport to delegates, I do not know why. But a number of commits before the latest one they did have `DllImport`. E.g. there is a mix of them at the end of this file: https://bitbucket.org/MDukhan/yeppp/src/40148ba4cdd00b03dfa880f6b7cecce83979c9d3/bindings/clr/sources-csharp/library/Library.cs?at=default

Going back to my StackOverflow link - I do think that delegates are ugly and cumbersome, and SO gurus also recommend keeping DllImport is it is possible. 

BTW, here is another my question on SO that was about how to pass comparer functions to LMDB: http://stackoverflow.com/questions/28578100/where-function-passed-as-unmanagedfunctionpointer-to-c-is-executed . Probably the only place where `UnmanagedFunctionPinter`s are useful.

**Comment by buybackoff** [comment]
To complete the discussion from my side, there was another discussion with NNanomsg: https://github.com/mhowlett/NNanomsg/issues/20

It looks like performance is not a big deal, it is more about convenience. But with this LMDB library, you could just throw away T4 and keep other code unchanged.

**Comment by CoreyKaylor** [comment]
Yeah, I'll continue forward with DllImport until it proves problematic. Oddly I actually prefer the delegate approach because it removes the need for public static methods everywhere. Due to the static state there are plenty of places that it has influenced design decisions that might be different without it. Again though, I'll continue on the path of keeping it around for now.

**Comment by CoreyKaylor** [comment]
@ilyalukyanov Looking for your sign-off before I head too much down this path.

**Comment by ilyalukyanov** [comment]
Hi @CoreyKaylor, yeah it sounds wonderful, dnx support is a really great enhancement for the library. Thank you for that.

I agree that build process needs to be simplified as the project is currently not conttribution-friendly

My only concern is storing native binaries in the repo. For windows and (I almost sure) OS X it's not a problem, but I don't think we can provide a universal .so file that works on every Linux (and moreover Unix-based) OS and every arch. Nevertheless, two options here could be:
- to leave it to developers and not include .so into the package
- add support only for several most popular OSs and (probably) distribute the library via native package manager.

I've also looked through the discussion here and my personal preference is still a T4 template plus `Dllimport`'s. I considered the `LoadLibrary` approach previously and liked it less than the existing one for the following reasons:
- The approach is imperative instead of the existing declarative one. There's no need to explain benifits of declarative approach.
- Instead of utilising P/Invoke support implemented inside of the runtime, custom code is used, which means we have to support it for every platform and understand diferences.
- I don't see what benifits it gives except a shorter and more common implementation.

However, my position is open here if you guys think it's an improvement, I'd be happy to consider the new implementation.

**Comment by CoreyKaylor** [comment]
Not quite ready to test yet, but my guess is that LoadLibrary will be required because there are no appdomain's + directories _currently_ to assume the application runs from. Everything is compiled and run from memory. The approach Kestrel uses is to infer the native dir from the Kestrel nuget path which can be derived through an interface called ILibraryManager.

I'm holding off on any strong opinions until the DllImport xplat story is flushed out for dnx.

I agree with regard to Linux native libs. The Kestrel project actually includes all but the linux lib and I think it would be easy enough to accomplish the same. Ideally anybody that uses the project should just be able to pull down the nuget and have it run without having to learn how to compile, or copy dll's around.

On a separate note. I've got a lot of the project structure converted over and tests passing again. It's a bit brute force so I'll take some time to clean it up before I push the branch public. I had to switch the test project over to Xunit because it's the only test lib right now that works on dnx.

I'm not too concerned with the specifics, just that we agree it's something we should support. It's likely this will live in a branch for a bit until targets stop moving. It's easy enough to publish pre-release nugets to the myget feed from a branch.

**Comment by CoreyKaylor** [comment]
It looks like LoadLibrary + DllImport is not an option currently on Linux and Mac w/dnx. The LoadLibrary and delegate option works fine though. I'm fine to resurrect it when something changes to fix the behavior.

**Comment by CoreyKaylor** [comment]
I think I've decided to unwind a little bit of what I've done in favor of a less intrusive change to make it easier for backwards compatibility with the previous approaches. I'll post more details once I give it a try and still like the result, but I think it will be to leverage the C#6 "using static" to provide alternative calls for the different runtimes conditionally compiled in. Won't work for the arch, but that's no different than the challenges faced today.

**Comment by CoreyKaylor** [comment]
I've pushed up a branch and opened up pull request https://github.com/ilyalukyanov/Lightning.NET/pull/49 that I don't plan to have pulled in for a bit.

**Comment by CoreyKaylor** [comment]
This has been merged into master. I will probably make a public release in the coming couple weeks.

**Comment by CoreyKaylor** [comment]
Just for follow-up on the discussion around DllImport. The CoreCLR now adds the ability for your DllImport to work with native libs included in your nuget package now. I've changed everything back to use DllImport again and noticed decent perf improvements from the change.

**Comment by buybackoff** [comment]
Could you please share a link about this native support from nuget? Is
LoadLibrary called automatically behind the scenes? They released RC
yesterday and I am thinking to start migration of my projects to DNX, and
many have native dependencies.

**Comment by CoreyKaylor** [comment]
http://blog.3d-logic.com/2015/11/10/using-native-libraries-in-asp-net-5/
