### ISSUE TITLE
Reset transactions must be aborted as well as active

### ISSUE THREAD

**Issue by buybackoff** [CoreyKaylor/Lightning.NET#60]
[This line](https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/LightningTransaction.cs#L322) should be:

```
if (State == TransactionState.Active || State == TransactionState.Reset)
            {
                Abort();
            }
```

http://symas.com/mdb/doc/group__mdb.html#ga02b06706f8a66249769503c4e88c56cd

**Comment by CoreyKaylor** [comment]
Looks like I might have to wait for the xunit runner to be released to the public feed before publishing this. They seem to be having problems with the private myget feed.

**Comment by CoreyKaylor** [comment]
Wasn't their feed after all. They switched to dnx46 and now I have as well, but that doesn't seem to be compatible with mono... Going to let the dust settle for a day or two before proceeding with a publish.

**Comment by buybackoff** [comment]
I was manually cherry-picking the good changes you made to the project into my private fork, but couldn't make the tests compile in VS2015RC. I am to scary to migrate to DNX until it is v.1.0.

It looks like on [this line](https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/LightningDatabase.cs#L96) `try..catch` should be only when `disposing == false`, on normal dispose that should never throw and we should not mute any exception.

Also, there are several places, when we open environment or database and do not check return code. `Execute` helper in the previous version was throwing a .NET exception when return code differs from zero, and that helper used [`mdb_strerror`](http://symas.com/mdb/doc/group__mdb.html#ga569e66c1e3edc1a6016b86719ee3d098) call to get a nice message from LMDB. Now we silently proceed, e.g. [here](https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/LightningDatabase.cs#L32) or [here](https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/LightningEnvironment.cs#L139). In the env case, we check if the path exist, but any other non-zero return code will not give a meaningful message: http://symas.com/mdb/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340

**Comment by CoreyKaylor** [comment]
You're partially right on the exception behavior. It looks like mdb_dbi_open is only partially handling error codes (I'll make sure it handles all of them). I've moved the checking into the static Lmdb class instead of littering it throughout the project. For instance, mdb_env_open example is here. 

https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/Native/Lmdb.cs#L150

Yeah, dnx stuff requires VS 2015 RTM. The compilation and test running should be pretty unintrusive because it's still compiling for .NET 4.5 as well and that doesn't require you to adopt dnx as a whole for your own projects. I have a local test project that I pull down from the private myget feed that runs the same unit tests with a .NET 4.5 project and they all pass as they do with the dnx environment.

**Comment by buybackoff** [comment]
Missed that `check`, sorry. Then it should be ok.

**Comment by CoreyKaylor** [comment]
I've removed the swallow everything try/catch and added a test for the finalizers. I think that was likely a remnant of a flurry of changes that I left behind.
